### ISSUE TITLE
Missing Data For Weapons

### ISSUE THREAD

**Issue by Chiyadesu** [wwylele/mhrice#17]
Everything looks pretty good!

The only part I've not managed to see,: <http://mhrise.mhrice.info/weapon/GreatSword_024.html> You've got the cost to craft/buy tags, but the buy cost isn't specified anywhere. 
The price for crafting is 66% of the "base_val" cost which you're showing, but the 12k cost for buying the item isn't shown. 

I can't see where this is handled though. 
On the site - you're showing the forge vs upgrade item costs where relevant but not the price. 
For the first in the tree, you're showing forge price + materials and also just price with no materials but that's not clearly specified either. 

Hoping you can help and clarify? :) 

# weapon keys: ['base_data', 'product', 'change', 'process', 'tree', 'name', 'explain']
Product being the buying info and process being the upgrade?

**Comment by wwylele** [comment]
I have updated the website. The `base_val` is the cost for upgrading, and the cost for crafting from scratch ("Forge") is `1.5 * base_cost`. The buying cost is `buy_val`. Btw, the particular weapon you linked cannot be bought using just money in game, so it has `buy_val = 0` and isn't shown on the page.

`product` forging. `process` is upgrading. There is no dedicated "buying" section because that's using only money and doesn't have much else info.

**Comment by wwylele** [comment]
I am closing this as I think the question has been answered. Feel free to reopen if there is still something unclear
