### ISSUE TITLE
Guild Card Special Investigation Medal Icon

### ISSUE THREAD

**Issue by gnoatx** [wwylele/mhrice#41]
Have you managed to extract the aforementioned icon from the game files? The one that appears by each monster on your guild card after you complete a special investigation for them. I've been making and updating a "completionist" tracker spreadsheet on Google Sheets ever since i started playing base Rise, and i think that's one of the few icons i still need.

**Comment by wwylele** [comment]
Yeah, it is in one of the gui/texture file, which you can extract by running a combination of `search-path`/`dump-tree`/`dump-tex` commands. I don't remember the exact file name.

**Comment by wwylele** [comment]
You can dump the file `gui/80_Texture/GuildCard_MR_IAM.tex`

**Comment by gnoatx** [comment]
I'm sorry about my ignorance, but neither i nor my programmer friend can figure this out, where is that file, and where do i run that command? 😰 He told me to download this repo as a zip file and run the commands you mentioned on Windows Terminal but none of the commands are recognized, nor can i find that file in the zip folder

**Comment by wwylele** [comment]
Try this:
 - Because I didn't release the binary, you need to install rust and build from source (see requirement in readme)
 - go to the root folder of this repo (either a zip download, or a git clone)
 - `cargo run -- dump -p "<game folder path>" -n "gui/80_Texture/GuildCard_MR_IAM.tex" -o GuildCard_MR_IAM.tex`
 - `cargo run -- dump-tex -t GuildCard_MR_IAM.tex -o GuildCard_MR_IAM.png`
 - `GuildCard_MR_IAM.png` file should appear and it is what you want

**Comment by gnoatx** [comment]
Thank you very much! And sorry for being a bother 😅
